[course]
name = "ABC123"
description = "Imaginary course for testing Pretor."

[assignment_1]
name = "Assignment 1"
description = "Description for the first assignment"
weight = 0.05
correctness = 70
style = 30

[assignment_2]
name = "Assignment 2"
description = "Description for the second assignment"
weight = 0.1
correctness = 70
style = 30

[assignment_3]
name = "Assignment 3"
description = "Description for the third assignment"
weight = 0.1
correctness = 70
style = 30

[midterm]
name = "Midterm"
weight = 0.2
problem_1 = 10
problem_2 = 10
problem_3 = 10
problem_4 = 70

[quiz1]
name = "Quiz 1"
weight = 0.1
problem_1 = 10
problem_2 = 10
problem_3 = 10

[quiz2]
name = "Quiz 2"
weight = 0.1
problem_1 = 10
problem_2 = 10
problem_3 = 10
problem_4 = 10
problem_5 = 10

[final]
name = "Final Exam"
weight = 0.35
problem_1 = 10
problem_2 = 10
problem_3 = 10
problem_4 = 30
problem_5 = 20
problem_6 = 20
problem_7 = 10
